/**
 * Factory Droid subscription registry, reviewed against the CLI version pinned
 * by `FACTORY_DROID_CLIENT_VERSION` (`wire/factory-droid.ts`). Native roster,
 * limits, credits, eligibility and routing facts are maintained here. Request
 * dialects live in compat/rules/providers/factory-droid.kdl.
 */

import type { GeneratedProvider } from "../models";
import {
	FACTORY_DROID_UPSTREAM_REGIONS,
	type FactoryDroidUpstream,
	type FactoryDroidWire,
} from "../wire/factory-droid";

/**
 * Effective upstream rotation for an inference region. The CLI's `We` resolves
 * eligible upstreams and `I` preserves raw registry order for fallback choice.
 * Explicit overrides constrain membership; otherwise filter by serving region.
 */
export function resolveFactoryDroidRotation(
	input: FactoryDroidModelInput,
	region: string | undefined,
): readonly FactoryDroidUpstream[] {
	const servingRegion = region === "eu" || region === "us" ? region : "global";
	const override =
		servingRegion === "eu"
			? input.euApiProviders
			: servingRegion === "us"
				? input.usApiProviders
				: input.globalApiProviders;
	if (override !== undefined) return input.apiProviders.filter(upstream => override.includes(upstream));
	return input.apiProviders.filter(upstream => FACTORY_DROID_UPSTREAM_REGIONS[upstream].includes(servingRegion));
}

/** Native limits for an inference region; EU overrides fall back to the registry defaults. */
export function factoryDroidRegionalLimits(
	input: FactoryDroidModelInput,
	region: string | undefined,
): { contextWindow: number; maxTokens: number } {
	return region === "eu"
		? {
				contextWindow: input.euContextWindow ?? input.contextWindow,
				maxTokens: input.euMaxTokens ?? input.maxTokens,
			}
		: { contextWindow: input.contextWindow, maxTokens: input.maxTokens };
}

export interface FactoryDroidModelInput {
	id: string;
	/** Display name, e.g. "Kimi K3 (Droid Core)". */
	name: string;
	wire: FactoryDroidWire;
	/** Native billing pool, independent from the request protocol. */
	billingPool: "core" | "standard";
	/** Native provider family used by live routing defaults. */
	routingFamily: "anthropic" | "openai" | "google" | "factory" | "xai";
	/** Canonical policy aliases explicitly registered by the native client. */
	policyAliases?: readonly string[];
	contextWindow: number;
	maxTokens: number;
	/** Upstream rotation list; the first entry is the default `x-api-provider`. */
	apiProviders: readonly FactoryDroidUpstream[];
	/** Explicit global-region rotation, distinct from the registry's full upstream set. */
	globalApiProviders?: readonly FactoryDroidUpstream[];
	usApiProviders?: readonly FactoryDroidUpstream[];
	/**
	 * Explicit rotation override for EU inference (the CLI's
	 * `regionOverrides.eu`), mirrored verbatim. Absent ⇒ the default rotation
	 * is filtered to upstreams serving the EU; an empty list means the model
	 * is unavailable for EU inference. Overrides may explicitly enable an
	 * upstream omitted from the EU upstream table (e.g. Mistral).
	 */
	euApiProviders?: readonly FactoryDroidUpstream[];
	/** EU context limits, when the official region override changes them. */
	euContextWindow?: number;
	euMaxTokens?: number;
	/**
	 * Droid Standard Credits rates: `input` is the per-token credit weight;
	 * `output` and `cacheRead` multiply that weight. Absent `output` defaults
	 * to 1; absent `cacheRead` means cache reads are not separately metered.
	 */
	credits?: {
		input: number;
		output?: number;
		cacheRead?: number;
	};
	/**
	 * Upstream catalog entry providing the raw-API list price for this model
	 * (the "$ what it would cost" counterfactual). Absent for Factory-only
	 * SKUs with no upstream equivalent: fast tiers are distinct SKUs (per
	 * variant-collapse cost-homogeneity doctrine) and preview codenames have
	 * no catalog entry.
	 */
	priceRef?: { provider: GeneratedProvider; modelId: string };
	/** Droid reasoning ladder; "off"/"none" entries mean thinking can be disabled. */
	supportedReasoningEfforts?: readonly string[];
	defaultReasoningEffort?: string;
	/**
	 * Statsig gate (from `GET /api/feature-flags`) that must be on for the
	 * account to see this model. Absent ⇒ always available.
	 */
	featureFlag?: string;
	/** Hard deprecation gate; when on, first-party clients hide this model. */
	deprecationFlag?: string;
	/** The registry requires a consent opt-in; absent policy must not expose it. */
	requiresExplicitOptIn?: boolean;
	/**
	 * Base model this entry is the fast tier of (the CLI's `baseVariant`).
	 * Org policy can withdraw fast tiers wholesale via managed settings'
	 * `isFastModelsAllowed`, and the presence of this field is what that gate
	 * keys off.
	 */
	baseVariant?: string;
	noImageSupport?: boolean;
}
export const FACTORY_DROID_MODELS: readonly FactoryDroidModelInput[] = [
	{
		id: "claude-fable-5.1",
		name: "Fable 5.1",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		euApiProviders: [],
		credits: { input: 4, output: 5, cacheRead: 0.025 },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		requiresExplicitOptIn: true,
	},
	{
		id: "claude-fable-5",
		name: "Fable 5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		euApiProviders: [],
		credits: { input: 4, output: 5 },
		priceRef: { provider: "anthropic", modelId: "claude-fable-5" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		requiresExplicitOptIn: true,
	},
	{
		id: "claude-opus-5-5",
		name: "Opus 5.5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 872000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic", "azure_anthropic", "snowflake"],
		credits: { input: 1.6, output: 5, cacheRead: 0.05 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		priceRef: { provider: "anthropic", modelId: "claude-opus-5-5" },
	},
	{
		id: "claude-opus-5-5-fast",
		name: "Opus 5.5 Fast Mode",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 872000,
		maxTokens: 128000,
		apiProviders: ["anthropic"],
		credits: { input: 3.2, output: 5, cacheRead: 0.05 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		featureFlag: "claude_opus_5_5_fast",
		baseVariant: "claude-opus-5-5",
	},
	{
		id: "claude-opus-5",
		name: "Opus 5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic", "azure_anthropic", "snowflake"],
		euApiProviders: ["bedrock_anthropic"],
		credits: { input: 2 },
		priceRef: { provider: "anthropic", modelId: "claude-opus-5" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "claude-opus-5-fast",
		name: "Opus 5 Fast Mode",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic"],
		credits: { input: 4 },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		baseVariant: "claude-opus-5",
	},
	{
		id: "claude-opus-4-8",
		name: "Opus 4.8",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic", "azure_anthropic", "snowflake"],
		euApiProviders: ["bedrock_anthropic"],
		credits: { input: 2 },
		priceRef: { provider: "anthropic", modelId: "claude-opus-4-8" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "claude-opus-4-8-fast",
		name: "Opus 4.8 Fast Mode",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic"],
		credits: { input: 4 },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		baseVariant: "claude-opus-4-8",
	},
	{
		id: "claude-opus-4-7",
		name: "Opus 4.7",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		euApiProviders: ["bedrock_anthropic"],
		credits: { input: 2 },
		priceRef: { provider: "anthropic", modelId: "claude-opus-4-7" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "claude-opus-4-6",
		name: "Opus 4.6",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic", "azure_anthropic", "snowflake"],
		credits: { input: 2 },
		priceRef: { provider: "anthropic", modelId: "claude-opus-4-6" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "claude-opus-4-5-20251101",
		name: "Opus 4.5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		usApiProviders: ["vertex_anthropic", "bedrock_anthropic"],
		contextWindow: 180000,
		maxTokens: 64000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		credits: { input: 2 },
		priceRef: { provider: "anthropic", modelId: "claude-opus-4-5-20251101" },
		supportedReasoningEfforts: ["off", "low", "medium", "high"],
		defaultReasoningEffort: "off",
	},
	{
		id: "claude-sonnet-5-5",
		name: "Sonnet 5.5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 872000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic", "azure_anthropic"],
		credits: { input: 0.8, output: 5 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		featureFlag: "claude_sonnet_5_5",
	},
	{
		id: "claude-sonnet-5",
		name: "Sonnet 5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 872000,
		maxTokens: 128000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic", "azure_anthropic"],
		credits: { input: 0.8, output: 5 },
		priceRef: { provider: "anthropic", modelId: "claude-sonnet-5" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "claude-sonnet-4-6",
		name: "Sonnet 4.6",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		contextWindow: 931000,
		maxTokens: 64000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		credits: { input: 1.2 },
		priceRef: { provider: "anthropic", modelId: "claude-sonnet-4-6" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "claude-sonnet-4-5-20250929",
		name: "Sonnet 4.5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		usApiProviders: ["vertex_anthropic", "bedrock_anthropic"],
		contextWindow: 180000,
		maxTokens: 32000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		credits: { input: 1.2 },
		priceRef: { provider: "anthropic", modelId: "claude-sonnet-4-5-20250929" },
		supportedReasoningEfforts: ["off", "low", "medium", "high"],
		defaultReasoningEffort: "off",
	},
	{
		id: "claude-haiku-4-5-20251001",
		name: "Haiku 4.5",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		usApiProviders: ["vertex_anthropic", "bedrock_anthropic"],
		contextWindow: 180000,
		maxTokens: 32000,
		apiProviders: ["anthropic", "vertex_anthropic", "bedrock_anthropic"],
		credits: { input: 0.4 },
		priceRef: { provider: "anthropic", modelId: "claude-haiku-4-5-20251001" },
		supportedReasoningEfforts: ["off", "low", "medium", "high"],
		defaultReasoningEffort: "off",
	},
	{
		id: "gpt-6-astra",
		name: "GPT-6 Astra",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "snowflake", "azure_openai"],
		euApiProviders: [],
		credits: { input: 4, output: 5 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		priceRef: { provider: "openai", modelId: "gpt-6-astra" },
	},
	{
		id: "gpt-6.1-sol",
		name: "GPT-6.1 Sol",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai"],
		euApiProviders: ["openai"],
		credits: { input: 0.8, output: 5, cacheRead: 0.05 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		featureFlag: "gpt_6_1_sol",
	},
	{
		id: "gpt-6-sol",
		name: "GPT-6 Sol",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai"],
		euApiProviders: ["openai"],
		credits: { input: 0.8, output: 5 },
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		priceRef: { provider: "openai", modelId: "gpt-6-sol" },
	},
	{
		id: "gpt-6-luna",
		name: "GPT-6 Luna",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai"],
		euApiProviders: ["openai"],
		credits: { input: 0.04, output: 5 },
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		featureFlag: "gpt_6_luna",
		priceRef: { provider: "openai", modelId: "gpt-6-luna" },
	},
	{
		id: "gpt-5.6-sol",
		name: "GPT-5.6 Sol",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai", "snowflake", "databricks"],
		euApiProviders: ["openai"],
		credits: { input: 2, output: 5 },
		priceRef: { provider: "openai", modelId: "gpt-5.6-sol" },
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.6-sol-fast",
		name: "GPT-5.6 Sol Fast Mode",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		policyAliases: ["gpt-5.6-fast"],
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 4, output: 5 },
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
		baseVariant: "gpt-5.6-sol",
	},
	{
		id: "gpt-5.6-terra",
		name: "GPT-5.6 Terra",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai", "snowflake", "databricks"],
		euApiProviders: ["openai"],
		credits: { input: 0.8, output: 6 },
		priceRef: { provider: "openai", modelId: "gpt-5.6-terra" },
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.6-luna",
		name: "GPT-5.6 Luna",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai", "snowflake", "databricks"],
		euApiProviders: ["openai"],
		credits: { input: 0.08, output: 6 },
		priceRef: { provider: "openai", modelId: "gpt-5.6-luna" },
		supportedReasoningEfforts: ["none", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.5",
		name: "GPT-5.5",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai", "snowflake", "databricks"],
		euApiProviders: ["openai"],
		credits: { input: 2, output: 6 },
		priceRef: { provider: "openai", modelId: "gpt-5.5" },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.5-fast",
		name: "GPT-5.5 Fast Mode",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 5, output: 6 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
		baseVariant: "gpt-5.5",
	},
	{
		id: "gpt-5.5-pro",
		name: "GPT-5.5 Pro",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai"],
		credits: { input: 12, output: 6 },
		priceRef: { provider: "openai", modelId: "gpt-5.5-pro" },
		supportedReasoningEfforts: ["medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.4",
		name: "GPT-5.4",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "bedrock_openai", "azure_openai", "databricks"],
		euApiProviders: ["openai"],
		credits: { input: 1, output: 6 },
		priceRef: { provider: "openai", modelId: "gpt-5.4" },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.4-fast",
		name: "GPT-5.4 Fast Mode",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 922000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 2, output: 6 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
		baseVariant: "gpt-5.4",
	},
	{
		id: "gpt-5.4-mini",
		name: "GPT-5.4 Mini",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 272000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 0.3, output: 6 },
		priceRef: { provider: "openai", modelId: "gpt-5.4-mini" },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "high",
	},
	{
		id: "gpt-5.4-mini-fast",
		name: "GPT-5.4 Mini Fast Mode",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 272000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 0.6, output: 6 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "high",
		baseVariant: "gpt-5.4-mini",
	},
	{
		id: "gpt-5.3-codex",
		name: "GPT-5.3-Codex",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		usApiProviders: [],
		contextWindow: 272000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 0.7 },
		priceRef: { provider: "openai", modelId: "gpt-5.3-codex" },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
	},
	{
		id: "gpt-5.3-codex-fast",
		name: "GPT-5.3-Codex Fast Mode",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		usApiProviders: [],
		contextWindow: 272000,
		maxTokens: 128000,
		apiProviders: ["openai"],
		credits: { input: 1.4, output: 8 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "medium",
		baseVariant: "gpt-5.3-codex",
	},
	{
		id: "gpt-5.2",
		name: "GPT-5.2",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "openai",
		contextWindow: 272000,
		maxTokens: 128000,
		apiProviders: ["openai", "azure_openai"],
		credits: { input: 0.7 },
		priceRef: { provider: "openai", modelId: "gpt-5.2" },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "low",
	},
	{
		id: "garnet-07-15",
		name: "Garnet 07/15 (Preview)",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		usApiProviders: [],
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.6 },
		supportedReasoningEfforts: ["medium", "high"],
		defaultReasoningEffort: "high",
		featureFlag: "garnet_0715",
	},
	{
		id: "gemini-3.1-pro-preview",
		name: "Gemini 3.1 Pro",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		policyAliases: ["gemini-3-pro-preview"],
		usApiProviders: [],
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.8 },
		priceRef: { provider: "google", modelId: "gemini-3.1-pro-preview" },
		supportedReasoningEfforts: ["low", "medium", "high"],
		defaultReasoningEffort: "high",
	},
	{
		id: "gemini-3.8-flash",
		name: "Gemini 3.8 Flash",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.6, output: 5 },
		supportedReasoningEfforts: ["low", "medium", "high"],
		defaultReasoningEffort: "high",
		priceRef: { provider: "google", modelId: "gemini-3.8-flash" },
	},
	{
		id: "gemini-3.7-flash",
		name: "Gemini 3.7 Flash",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.6, output: 5 },
		supportedReasoningEfforts: ["low", "medium", "high"],
		defaultReasoningEffort: "high",
		priceRef: { provider: "google", modelId: "gemini-3.7-flash" },
	},
	{
		id: "gemini-3.6-flash",
		name: "Gemini 3.6 Flash",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.6, output: 5 },
		priceRef: { provider: "google", modelId: "gemini-3.6-flash" },
		supportedReasoningEfforts: ["low", "medium", "high"],
		defaultReasoningEffort: "high",
	},
	{
		id: "gemini-3.5-flash",
		name: "Gemini 3.5 Flash",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.6 },
		priceRef: { provider: "google", modelId: "gemini-3.5-flash" },
		supportedReasoningEfforts: ["minimal", "low", "medium", "high"],
		defaultReasoningEffort: "high",
	},
	{
		id: "gemini-3-flash-preview",
		name: "Gemini 3 Flash",
		wire: "google-generate",
		billingPool: "standard",
		routingFamily: "google",
		usApiProviders: [],
		contextWindow: 1000000,
		maxTokens: 65536,
		apiProviders: ["google"],
		credits: { input: 0.2 },
		priceRef: { provider: "google", modelId: "gemini-3-flash-preview" },
		supportedReasoningEfforts: ["minimal", "low", "medium", "high"],
		defaultReasoningEffort: "high",
	},
	{
		id: "inkling",
		name: "Inkling",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 1007232,
		maxTokens: 32768,
		apiProviders: ["fireworks"],
		credits: { input: 0.4, output: 4.05, cacheRead: 0.17 },
		supportedReasoningEfforts: ["off", "minimal", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		priceRef: { provider: "fireworks", modelId: "inkling" },
	},
	{
		id: "mistral-medium-3.5",
		name: "Mistral Medium 3.5",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 192000,
		maxTokens: 64000,
		apiProviders: ["mistral"],
		euApiProviders: ["mistral"],
		credits: { input: 0.6, output: 5 },
		supportedReasoningEfforts: ["off", "high"],
		defaultReasoningEffort: "high",
	},
	{
		id: "glm-5.3-flash",
		name: "GLM-5.3-Flash",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 917504,
		maxTokens: 131072,
		apiProviders: ["fireworks", "baseten", "databricks"],
		credits: { input: 0.06, output: 3.34, cacheRead: 0.2 },
		supportedReasoningEfforts: ["low", "high", "max"],
		defaultReasoningEffort: "high",
		priceRef: { provider: "fireworks", modelId: "glm-5.3-flash" },
	},
	{
		id: "glm-5.3",
		name: "GLM-5.3",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 908928,
		maxTokens: 131072,
		apiProviders: ["fireworks", "baseten", "mistral", "databricks"],
		globalApiProviders: ["fireworks", "baseten", "databricks"],
		euApiProviders: ["mistral"],
		credits: { input: 0.56, output: 3.15 },
		priceRef: { provider: "fireworks", modelId: "glm-5.3" },
		supportedReasoningEfforts: ["low", "high", "max"],
		defaultReasoningEffort: "max",
		noImageSupport: true,
	},
	{
		id: "glm-5.2",
		name: "GLM-5.2",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		policyAliases: ["glm-5.1"],
		contextWindow: 908928,
		maxTokens: 131072,
		apiProviders: ["baseten", "mistral"],
		globalApiProviders: ["baseten"],
		euApiProviders: ["mistral"],
		euContextWindow: 200000,
		euMaxTokens: 65536,
		credits: { input: 0.56, output: 3.15 },
		priceRef: { provider: "fireworks", modelId: "glm-5.2" },
		supportedReasoningEfforts: ["off", "high", "max"],
		defaultReasoningEffort: "high",
		noImageSupport: true,
	},
	{
		id: "glm-5.2-fast",
		name: "GLM-5.2 Fast",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		policyAliases: ["glm-5p2-fast"],
		contextWindow: 393216,
		maxTokens: 131072,
		apiProviders: ["baseten"],
		credits: { input: 0.84, output: 3.2 },
		supportedReasoningEfforts: ["off", "high", "max"],
		defaultReasoningEffort: "high",
		featureFlag: "glm_5_2_fast",
		baseVariant: "glm-5.2",
		noImageSupport: true,
	},
	{
		id: "kimi-k3",
		name: "Kimi K3",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 196608,
		maxTokens: 65536,
		apiProviders: ["fireworks", "baseten", "databricks"],
		credits: { input: 1.2, output: 5 },
		priceRef: { provider: "fireworks", modelId: "kimi-k3" },
		supportedReasoningEfforts: ["off", "low", "high", "max"],
		defaultReasoningEffort: "high",
	},
	{
		id: "qwen3.8-max",
		name: "Qwen3.8 Max",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 131072,
		maxTokens: 131072,
		apiProviders: ["fireworks"],
		credits: { input: 0.8, output: 3 },
		supportedReasoningEfforts: ["low", "medium", "xhigh"],
		defaultReasoningEffort: "xhigh",
		noImageSupport: true,
		priceRef: { provider: "fireworks", modelId: "qwen3.8-max" },
	},
	{
		id: "nemotron-3-ultra",
		name: "Nemotron 3 Ultra",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 136464,
		maxTokens: 65536,
		apiProviders: ["baseten", "fireworks"],
		credits: { input: 0.24, output: 4 },
		priceRef: { provider: "baseten", modelId: "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B" },
		supportedReasoningEfforts: ["off", "high"],
		defaultReasoningEffort: "high",
		noImageSupport: true,
	},
	{
		id: "deepseek-v4.1-flash",
		name: "DeepSeek V4.1 Flash",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 908928,
		maxTokens: 131072,
		apiProviders: ["fireworks", "baseten", "databricks"],
		credits: { input: 0.12, output: 4, cacheRead: 0.024 },
		supportedReasoningEfforts: ["off", "low", "high", "max"],
		defaultReasoningEffort: "high",
		featureFlag: "deepseek_v4_1_flash",
		priceRef: { provider: "fireworks", modelId: "deepseek-v4.1-flash" },
	},
	{
		id: "deepseek-v4-flash-0731",
		name: "DeepSeek V4 Flash 0731",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 908928,
		maxTokens: 131072,
		apiProviders: ["fireworks", "baseten"],
		credits: { input: 0.176, output: 3, cacheRead: 0.032 },
		priceRef: { provider: "fireworks", modelId: "deepseek-v4-flash-0731" },
		supportedReasoningEfforts: ["off", "low", "high", "max"],
		defaultReasoningEffort: "high",
		deprecationFlag: "deprecate_deepseek_v4_flash_0731",
		noImageSupport: true,
	},
	{
		id: "deepseek-v4-pro",
		name: "DeepSeek V4 Pro",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 908928,
		maxTokens: 131072,
		apiProviders: ["fireworks", "baseten"],
		credits: { input: 0.528, output: 3, cacheRead: 0.034 },
		priceRef: { provider: "fireworks", modelId: "deepseek-v4-pro" },
		supportedReasoningEfforts: ["off", "low", "high", "max"],
		defaultReasoningEffort: "high",
		deprecationFlag: "deprecate_deepseek_v4_pro",
		noImageSupport: true,
	},
	{
		id: "minimax-m3",
		name: "MiniMax M3",
		wire: "openai-completions",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 448000,
		maxTokens: 64000,
		apiProviders: ["fireworks"],
		credits: { input: 0.12, output: 4 },
		priceRef: { provider: "fireworks", modelId: "minimax-m3" },
		supportedReasoningEfforts: ["high"],
		defaultReasoningEffort: "high",
		featureFlag: "minimax_m3",
	},
	{
		id: "grok-4.7",
		name: "Grok 4.7",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "xai",
		contextWindow: 436644,
		maxTokens: 63356,
		apiProviders: ["xai"],
		credits: { input: 0.8, output: 3, cacheRead: 0.25 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "high",
		priceRef: { provider: "xai", modelId: "grok-4.7" },
	},
	{
		id: "grok-4.6",
		name: "Grok 4.6",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "xai",
		contextWindow: 200000,
		maxTokens: 63356,
		apiProviders: ["xai"],
		credits: { input: 0.8, output: 3, cacheRead: 0.25 },
		supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
		defaultReasoningEffort: "high",
		priceRef: { provider: "xai", modelId: "grok-4.6" },
	},
	{
		id: "grok-4.5",
		name: "Grok 4.5",
		wire: "openai-responses",
		billingPool: "standard",
		routingFamily: "xai",
		usApiProviders: [],
		contextWindow: 200000,
		maxTokens: 63356,
		apiProviders: ["xai"],
		credits: { input: 0.8, output: 3, cacheRead: 0.15 },
		priceRef: { provider: "xai", modelId: "grok-4.5" },
		supportedReasoningEfforts: ["low", "medium", "high"],
		defaultReasoningEffort: "high",
	},
	{
		id: "atlas-07-21",
		name: "Atlas 07/21 (Preview)",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		usApiProviders: [],
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic"],
		credits: { input: 2 },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		featureFlag: "atlas_0721",
	},
	{
		id: "aster-07-15",
		name: "Aster 07/15 (Preview)",
		wire: "anthropic-messages",
		billingPool: "standard",
		routingFamily: "anthropic",
		usApiProviders: [],
		contextWindow: 867000,
		maxTokens: 128000,
		apiProviders: ["anthropic"],
		credits: { input: 2 },
		supportedReasoningEfforts: ["off", "low", "medium", "high", "xhigh", "max"],
		defaultReasoningEffort: "high",
		featureFlag: "aster_0715",
	},
	{
		id: "minimax-m2.7",
		name: "MiniMax M2.7",
		wire: "anthropic-messages",
		billingPool: "core",
		routingFamily: "factory",
		contextWindow: 196600,
		maxTokens: 64000,
		apiProviders: ["fireworks"],
		credits: { input: 0.12, output: 4 },
		priceRef: { provider: "fireworks", modelId: "minimax-m2.7" },
		supportedReasoningEfforts: ["high"],
		defaultReasoningEffort: "high",
		noImageSupport: true,
	},
];

/** Model id → registry entry, for the provider wrapper's per-model wire config. */
export const FACTORY_DROID_MODEL_META: Readonly<Record<string, FactoryDroidModelInput>> = Object.fromEntries(
	FACTORY_DROID_MODELS.map(model => [model.id, model]),
);

/** Factory subscription billing pool; unknown IDs have no inferred entitlement. */
export function factoryDroidPoolForModel(modelId: string): "core" | "standard" | undefined {
	const meta = FACTORY_DROID_MODEL_META[modelId];
	if (!meta) return undefined;
	return meta.billingPool;
}
